apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: sample
  name: sample
spec: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-delete
  namespace: sample
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-delete
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-delete
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-delete
subjects:
- kind: ServiceAccount
  name: pod-delete
  namespace: sample
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kubectl
  name: kubectl
  namespace: sample
spec:
  containers:
  - image: bitnami/kubectl:latest
    imagePullPolicy: Always
    name: kubectl
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: pod-delete
  serviceAccountName: pod-delete